// <auto-generated />
using System;
using Loto3000.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Loto3000.DataAccess.Migrations
{
    [DbContext(typeof(Loto3000DbContext))]
    partial class Loto3000DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Loto3000.Domain.Models.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("DrawnAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DrawnNumbers")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("InitiatedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DrawnAt");

                    b.HasIndex("InitiatedByAdminId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("Draws", null, t =>
                        {
                            t.HasCheckConstraint("CK_Draws_NumbersJson", "ISJSON([DrawnNumbers]) = 1");
                        });
                });

            modelBuilder.Entity("Loto3000.Domain.Models.LotterySession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("EndTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("SessionNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionNumber")
                        .IsUnique();

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("LotterySessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_LotterySessions_Lifecycle", "([Status] = 0 AND [EndTime] IS NULL) OR ([Status] = 1 AND [EndTime] IS NOT NULL AND [EndTime] >= [StartTime])");

                            t.HasCheckConstraint("CK_LotterySessions_Number", "[SessionNumber] > 0");
                        });
                });

            modelBuilder.Entity("Loto3000.Domain.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Numbers")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "SubmittedAt");

                    b.HasIndex("UserId", "SubmittedAt");

                    b.ToTable("Tickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tickets_NumbersJson", "ISJSON([Numbers]) = 1");
                        });
                });

            modelBuilder.Entity("Loto3000.Domain.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "[Role] IN (0, 1)");
                        });
                });

            modelBuilder.Entity("Loto3000.Domain.Models.Winner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DrawId")
                        .HasColumnType("int");

                    b.Property<int>("MatchedCount")
                        .HasColumnType("int");

                    b.Property<string>("MatchedNumbers")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Prize")
                        .HasColumnType("int");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("WonAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.HasIndex("WonAt")
                        .IsDescending();

                    b.HasIndex("DrawId", "TicketId")
                        .IsUnique();

                    b.ToTable("Winners", null, t =>
                        {
                            t.HasCheckConstraint("CK_Winners_NumbersJson", "ISJSON([MatchedNumbers]) = 1");

                            t.HasCheckConstraint("CK_Winners_Prize", "[MatchedCount] BETWEEN 3 AND 7 AND [Prize] = [MatchedCount]");
                        });
                });

            modelBuilder.Entity("Loto3000.Domain.Models.Draw", b =>
                {
                    b.HasOne("Loto3000.Domain.Models.User", null)
                        .WithMany()
                        .HasForeignKey("InitiatedByAdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Loto3000.Domain.Models.LotterySession", "Session")
                        .WithOne("Draw")
                        .HasForeignKey("Loto3000.Domain.Models.Draw", "SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Loto3000.Domain.Models.Ticket", b =>
                {
                    b.HasOne("Loto3000.Domain.Models.LotterySession", "Session")
                        .WithMany("Tickets")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Loto3000.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Loto3000.Domain.Models.Winner", b =>
                {
                    b.HasOne("Loto3000.Domain.Models.Draw", "Draw")
                        .WithMany()
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Loto3000.Domain.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Loto3000.Domain.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Draw");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Loto3000.Domain.Models.LotterySession", b =>
                {
                    b.Navigation("Draw");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
